<?php

/**
 * @file
 * Defines features and functions common to the commerce delivery module.
 */

/**
 * Implements hook_permission().
 */
function commerce_delivery_permission() {
  $permissions = commerce_entity_access_permissions('commerce_delivery') + array(
    'commerce_delivery_administer_deliveries' => array(
      'title' => t('Adminster deliveries'),
      'description' => t('Allows users to administer deliveries.'),
      'restrict access' => TRUE,
    ),
    'commerce_delivery_manage_deliveries' => array(
      'title' => t('Manage deliveries'),
      'description' => t('Allows users to manage deliveries.'),
      'restrict access' => TRUE,
    ),
    'commerce_delivery_rules_access' => array(
      'title' => t('Adminster deliveries rules'),
      'description' => t('Allows users to adminster deliveries rules.'),
      'restrict access' => TRUE,
    ),
  );
  return $permissions;
}

/**
 * Implements hook_entity_info().
 */
function commerce_delivery_entity_info() {
  $return = array(
    'commerce_delivery' => array(
      'label' => t('Commerce Delivery'),
      'controller class' => 'CommerceDeliveryEntityController',
      'metadata controller class' => '',
      'base table' => 'commerce_delivery',
      'uri callback' => 'commerce_delivery_uri',
      'fieldable' => TRUE,
      'token_type' => 'commerce-delivery',
      'entity keys' => array(
        'id' => 'delivery_id',
        'bundle' => 'type',
        'label' => 'delivery_id',
      ),
      'bundle keys' => array(
        'bundle' => 'type',
      ),
      'bundles' => array(
        'commerce_delivery' => array(
          'label' => 'Delivery',
          'admin' => array(
            'path' => 'admin/commerce/config/delivery',
            'access arguments' => array('administer deliveries'),
          ),
        ),
      ),
      'view modes' => array(
        'full' => array(
          'label' => t('Full Delivery'),
          'custom settings' => FALSE,
        ),
        'teaser' => array(
          'label' => t('Teaser'),
          'custom settings' => TRUE,
        ),
      ),
      'load_hook' => 'commerce_delivery_load',
      'creation callback' => 'commerce_delivery_create',
      'save callback' => 'commerce_delivery_save',
      'deletion callback' => 'commerce_delivery_delete',
      'access callback' => 'commerce_entity_access',
      'access arguments' => array(
        'user key' => 'uid',
        'access tag' => 'commerce_delivery_access',
      ),
      'permission labels' => array(
        'singular' => t('delivery'),
        'plural' => t('deliveries'),
      ),
    ),
  );
  return $return;
}

/**
 * Checks order access for various operations.
 *
 * @param $op
 *   The operation being performed. One of 'view', 'update', 'create' or
 *   'delete'.
 * @param delivery
 *   Optionally a delivery to check access for.
 * @param $account
 *   The user to check for. Leave it to NULL to check for the current user.
 * 
 * @return boolean
 */
function commerce_delivery_access($op, $delivery = NULL, $account = NULL) {
  return commerce_entity_access($op, $delivery, $account, 'commerce_delivery');
}

/**
 * Implementation of hook_query_commerce_order_access_alter().
 *
 * @param \QueryAlterableInterface $query
 */
function commerce_delivery_query_commerce_delivery_access_alter(QueryAlterableInterface $query) {
  commerce_entity_access_query_alter($query, 'commerce_delivery');
}


/**
 * Callback returning delivery url.
 *
 * @param $delivery
 *
 * @return array
 */
function commerce_delivery_uri($delivery) {
  return array( 'path' => 'admin/commerce/deliveries/' . $delivery->delivery_id . '/view');
}

/**
 * Create a new delivery object.
 *
 * @param $values
 *   List of initial object attributes.
 * @return
 *   The new commerce_delivery object.
 */
function commerce_delivery_create($values) {
  return entity_get_controller('commerce_delivery')->create($values);
}

/**
 * Saves a delivery.
 *
 * @param $delivery
 *   The full delivery object to save. If $delivery->delivery_id is empty, a new delivery
 *     will be created.
 *
 * @return
 *   The saved delivery object.
 */
function commerce_delivery_save($delivery) {
  return entity_get_controller('commerce_delivery')->save($delivery);
}

/**
 * Callback for getting order properties.
 *
 * @see commerce_delivery_entity_property_info()
 *
 * @param $delivery
 * @param array $options
 * @param $name
 *
 * @return string
 */
function commerce_delivery_get_properties($delivery, array $options, $name) {
  switch ($name) {
//    case 'view-url':
//      return url('delivery/' . $delivery->delivery_id, $options);
    case 'admin-url':
      return url('admin/commerce/deliveries/' . $delivery->delivery_id . '/view', $options);
    case 'edit-url':
      return url('admin/commerce/deliveries/' . $delivery->delivery_id . '/edit', $options);
  }
  return NULL;
}

/**
 * Loads a delivery by ID.
 *
 * @param $delivery_id
 *
 * @return bool|mixed
 */
function commerce_delivery_load($delivery_id) {
  $delivery = commerce_delivery_load_multiple(array($delivery_id), array());
  return $delivery ? reset($delivery) : FALSE;
}

/**
 * Loads multiple deliveries by ID or based on a set of matching conditions.
 *
 * @see entity_load()
 *
 * @param $delivery_ids
 *   An array of delivery IDs.
 * @param $conditions
 *   An array of conditions on the {commerce_delivery} table in the form
 *     'field' => $value.
 * @param $reset
 *   Whether to reset the internal delivery loading cache.
 *
 * @return
 *   An array of delivery objects indexed by delivery_id.
 */
function commerce_delivery_load_multiple($delivery_ids = array(), $conditions = array(), $reset = FALSE) {
  return entity_load('commerce_delivery', $delivery_ids, $conditions, $reset);
}

/**
 * Implements hook_menu().
 */
function commerce_delivery_menu() {
  $items['admin/commerce/deliveries/add'] = array(
    'title' => 'Create a delivery ',
    'description' => 'Create a new delivery for the specified order.',
    'page callback' => 'commerce_delivery_add',
    'access arguments' => array('commerce_delivery_administer_deliveries'),
    'weight' => 10,
    'type' => MENU_CALLBACK,
  );
  $items['admin/commerce/deliveries/add/%order_id'] = array(
    'title' => 'Create a delivery ',
    'description' => 'Create a new delivery for the specified order.',
    'page callback' => 'commerce_delivery_add',
    'page arguments' => array(4),
    'access arguments' => array('commerce_delivery_administer_deliveries'),
    'weight' => 10,
    'type' => MENU_CALLBACK,
  );
  $items['admin/commerce/config/delivery'] = array(
    'title' => 'Delivery settings',
    'description' => 'Configure general delivery settings, fields, and displays.',
    'page callback' => 'drupal_get_form',
    'page arguments' => array('commerce_delivery_settings_form'),
    'access arguments' => array('commerce_delivery_administer_deliveries'),
    'weight' => 0,
    'type' => MENU_NORMAL_ITEM,
  );
  $items['admin/commerce/config/delivery/settings'] = array(
    'title' => 'Settings',
    'weight' => 0,
    'type' => MENU_DEFAULT_LOCAL_TASK,
  );
  // this is ugly, but couldn't find a better way.
  // views can't set a contextual inline tab
  $items['admin/commerce/orders/%commerce_order/deliveries'] = array(
    'title' => 'Deliveries',
    'page callback' => 'commerce_delivery_by_order_view',
    'page arguments' => array(3),
    'access callback' => 'commerce_order_access',
    'access arguments' => array('update', 3),
    'type' => MENU_LOCAL_TASK,
    'weight' => 0,
    'context' => MENU_CONTEXT_PAGE | MENU_CONTEXT_INLINE,
  );
  $items['admin/commerce/orders/%commerce_order/deliveries/move/%commerce_line_item/%commerce_delivery'] = array(
    'title' => 'Move line item to a delivery',
    'page callback' => 'commerce_delivery_move_item',
    'page arguments' => array(3, 6, 7),
    'access callback' => 'commerce_order_access',
    'access arguments' => array('update', 3),
    'weight' => 10,
    'type' => MENU_CALLBACK,
  );
 $items['admin/commerce/deliveries/%commerce_delivery'] = array(
    'title' => 'View Delivery',
    'page callback' => 'commerce_delivery_delivery_view',
    'page arguments' => array(3),
    'access arguments' => array('commerce_delivery_administer_deliveries'),
    'weight' => -10,
  );
  $items['admin/commerce/deliveries/%commerce_delivery/view'] = array(
    'title' => 'View',
    'type' => MENU_DEFAULT_LOCAL_TASK,
    'weight' => -10,
    'context' => MENU_CONTEXT_PAGE | MENU_CONTEXT_INLINE,
  );
  $items['admin/commerce/deliveries/%commerce_delivery/edit'] = array(
    'title' => 'Edit',
    'type' => MENU_LOCAL_TASK,
    'page callback' => 'drupal_get_form',
    'page arguments' => array('commerce_delivery_form', 3, 'edit'),
    'access arguments' => array('commerce_delivery_administer_deliveries'),
    'weight' => 5,
    'context' => MENU_CONTEXT_PAGE | MENU_CONTEXT_INLINE,
  );
  $items['admin/commerce/deliveries/%commerce_delivery/delete'] = array(
    'title' => 'Delete',
    'type' => MENU_LOCAL_TASK,
    'page callback' => 'drupal_get_form',
    'page arguments' => array('commerce_delivery_page_delete_confirm_form', 3),
    'access arguments' => array('commerce_delivery_administer_deliveries'),
    'weight' => 20,
    'context' => MENU_CONTEXT_INLINE,
  );

  return $items;
}

/**
 * @param $delivery
 * @param string $view_mode
 * @param bool $breadcrumb
 * @return bool
 */
function commerce_delivery_delivery_view($delivery, $view_mode = 'full', $breadcrumb = TRUE) {
/*
  // Set the breadcrumb for the appropriate view mode if specified.
  if ($breadcrumb) {
    commerce_order_ui_set_breadcrumb();
  }

  drupal_add_css(drupal_get_path('module', 'commerce_order') . '/theme/commerce_order.theme.css');
*/
  return entity_view('commerce_delivery', array($delivery->delivery_id => $delivery), $view_mode, NULL, TRUE);
}


/**
 * Implements hook_field_extra_fields().
 */
function commerce_delivery_field_extra_fields() {
  $return = array();
  $return['commerce_delivery']['commerce_delivery'] = array(
    'form' => array(
      'delivery_id' => array(
        'label' => t('ID'),
        'description' => t('Delivery ID'),
        'weight' => 1,
      ),
      'order_id' => array(
        'label' => t('OID'),
        'description' => t('Order ID'),
        'weight' => 1,
      ),
      'status' => array(
        'label' => t('Status'),
        'description' => t('Delivery status'),
        'weight' => 1,
      ),
    ),
    'display' => array(
      'delivery_id' => array(
        'label' => t('ID'),
        'description' => t('Delivery ID'),
        'weight' => 1,
      ),
      'order_id' => array(
        'label' => t('OID'),
        'description' => t('Order ID'),
        'weight' => 1,
      ),
      'status' => array(
        'label' => t('Status'),
        'description' => t('Delivery status'),
        'weight' => 1,
      ),
    ),
  );
  return $return;
}

/**
 * Page callback.
 *
 * @param $order
 *
 * @return string
 */
function commerce_delivery_by_order_view($order) {
  $destination = drupal_get_destination();
  $output = '<ul class="action-links"><li>';
  $output .= l(t('Add delivery'), 'admin/commerce/deliveries/add/' . $order->order_id,
                        array('query' => $destination));

  $output .= '</li></ul>';
  $output .= views_embed_view('commerce_delivery_by_order', 'default', $order->order_id);
  return $output;
}

/**
 * Page callback for moving a line item to a delivery.
 *
 * @param $order
 *  The order entity.
 * @param $line_item
 *  The line item entity.
 * @param $delivery
 *  The delivery entity.
 */
function commerce_delivery_move_item($order, $line_item, $delivery) {
  // Validate the token from the link.
  $token = $_REQUEST['token'];
  if ($token != commerce_delivery_get_token($order->order_id, $line_item->line_item_id, $delivery->delivery_id)) {
    drupal_set_message(t('Invalid token.'), 'error');
    drupal_access_denied();
    return;
  }

  // Validate that the line item belongs to the order.
  if ($line_item->order_id != $order->order_id) {
    drupal_set_message(t('Invalid parameters.'), 'error');
    drupal_access_denied();
    return;
  }

  $wrapper = entity_metadata_wrapper('commerce_line_item', $line_item);
  // setting the deliver ref
  $wrapper->delivery_ref = $delivery->delivery_id;
  commerce_line_item_save($line_item);
  drupal_set_message(t('Item %item has been moved to delivery %delivery.', array(
    '%item' => $line_item->line_item_label,
    '%delivery' => $delivery->delivery_id,
  )));
  drupal_goto();
}

/**
 * Get a token to protect delivery action links.
 *
 * @param $order_id
 *  The order entity.
 * @param $line_item_id
 *  The line item entity.
 * @param $delivery_id
 *  The delivery entity.
 *
 * @return string A token string.
 * A token string.
 */
function commerce_delivery_get_token($order_id, $line_item_id, $delivery_id) {
  return drupal_get_token(implode('-', array('commerce_delivery', $order_id, $line_item_id, $delivery_id)));
}

/**
 * Page callback for adding a new delivery.
 *
 * @param $order_id
 *   ID of the order which to attach the delivery to
 *
 * @return array
 */
function commerce_delivery_add($order_id = NULL) {
  // TODO: check order_id
  if ($order_id == '') {
    return t('Required Order ID missing.');
  }

  $delivery = commerce_delivery_create(array('order_id' => $order_id));
  
  return drupal_get_form('commerce_delivery_form', $delivery, 'add');
}

/**
 * Helper function that return status values as options.
 *
 * @return array
 *   An array of status labels indexed by their id.
 */
function commerce_delivery_get_status() {
  return variable_get_value('commerce_delivery_status_options');
}

/**
 * Returns the human readable title of a delivery status.
 *
 * @param $id
 *   id of the status
 *
 * @return string
 *   string containing the human readable title for the specified state. If a state
 *     is specified that does not exist, this function returns FALSE.
 */
function commerce_delivery_status_get_title($id = NULL) {
  $states = commerce_delivery_get_status();

  // Return a state title if specified and it exists.
  if (isset($states[$id])) {
      return check_plain($states[$id]);
    }
  return FALSE;
}

/**
 * @param $form
 * @param $form_state
 * @param $delivery
 * @param string $op
 * @return mixed
 */
function commerce_delivery_form($form, &$form_state, $delivery, $op = 'edit'){
  $form_state['commerce_delivery'] = $delivery;
  $form_state['op'] = $op;
  field_attach_form('commerce_delivery', $delivery, $form, $form_state);
  
  $form['status'] = array(
    '#type' => 'select',
    '#title' => t('Status'),
    '#options' => commerce_delivery_get_status(),
    '#default_value' => ($op == 'edit') ? $delivery->status : variable_get('commerce_delivery_default_status', ''),
    '#required' => TRUE,
  );
  $form['actions'] = array(
    '#type' => 'container',
    '#attributes' => array('class' => array('form-actions')),
    '#weight' => 400,
  );
  $form['actions']['submit'] = array(
    '#type' => 'submit',
    '#value' => t('Save delivery'),
    '#weight' => 40,
  );
  if(empty($delivery->is_new) && $op == 'edit'){
    $form['actions']['delete'] = array(
      '#type' => 'submit',
      '#value' => t('Delete delivery'),
      '#weight' => 45,
      '#limit_validation_errors' => array(),
      '#submit' => array('commerce_delivery_form_submit_delete')
    );
  }
  $form['#submit'][] = 'commerce_delivery_form_submit';
  return $form;
}

/**
 * @param $form
 * @param $form_state
 */
function commerce_delivery_form_validate($form, &$form_state) {
  field_attach_form_validate('commerce_delivery', $form_state['commerce_delivery'], $form, $form_state);
}

/**
 * @param $form
 * @param $form_state
 */
function commerce_delivery_form_submit($form, &$form_state){
  $commerce_delivery = &$form_state['commerce_delivery'];
  $commerce_delivery->status = $form_state['values']['status'];
  
  field_attach_submit('commerce_delivery', $commerce_delivery, $form, $form_state);
  
  commerce_delivery_save($commerce_delivery);
  
  $form_state['redirect'] = "admin/commerce/deliveries";
  
  drupal_set_message(t('Delivery saved.'));
}

/**
 * Delivery form submit handler for the delete button.
 *
 * @param $form
 * @param $form_state
 */
function commerce_delivery_form_submit_delete($form, &$form_state) {
  $form_state['redirect'] = 'admin/commerce/deliveries/' . $form_state['commerce_delivery']->delivery_id . '/delete';
}

/**
 * Confirm form for deleting a profile.
 *
 * @param $form
 * @param $form_state
 * @param $delivery
 *  A delivery entity.
 *
 * @return array
 */
function commerce_delivery_page_delete_confirm_form($form, &$form_state, $delivery) {
  $form_state['commerce_delivery'] = $delivery;
  $form['#submit'][] = 'commerce_delivery_page_delete_confirm_form_submit';
  
  $confirm_question = t('Are you sure you want to delete delivery @label?', array('@label' => $delivery->delivery_id));
  $uri = commerce_delivery_uri($delivery);
  return confirm_form($form, $confirm_question, $uri['path']);
}

/**
 * Submit handler for deleting a delivery.
 *
 * @param $form
 * @param $form_state
 */
function commerce_delivery_page_delete_confirm_form_submit($form, &$form_state) {
  $delivery = $form_state['commerce_delivery'];

  if (commerce_delivery_delete($delivery->delivery_id)) {
    drupal_set_message(t('Delivery @id has been deleted.', array('@id' => $delivery->delivery_id)));
    watchdog('commerce_order', 'Deleted delivery @id.', array('@id' => $delivery->delivery_id), WATCHDOG_NOTICE);
  }
  else {
    drupal_set_message(t('Delivery @id could not be deleted.', array('@id' => $delivery->delivery_id)), 'error');
  }

  $form_state['redirect'] = 'admin/commerce/deliveries';
}

/**
 * Delete a delivery entity.
 *
 * @param $delivery_id
 *  The delivery entity id to delete.
 */
function commerce_delivery_delete($delivery_id) {
  return commerce_delivery_delete_multiple(array($delivery_id));
}

function commerce_delivery_delete_multiple($delivery_ids) {
  return entity_get_controller('commerce_delivery')->delete($delivery_ids);
}

function commerce_delivery_variable_info($options) {
  $variables['commerce_delivery_status_options'] = array(
    'type' => 'properties',
    'title' => t('Delivery status options', array(), $options),
    'description' => t('Supply status options. Format is "id|label". Take note that lower id get priority when assigning items to random deliveries.', array(), $options),
    'default' => array(
      0 => 'new',
      1 => 'pending',
      2 => 'delivered',
      3 => 'on hold',
      4 => 'cancelled',
    ),
  );
  $variables['commerce_delivery_default_status'] = array(
    'type' => 'select',
    'title' => t('Delivery default status', array(), $options),
    'description' => t('Select the default status assigned to a new delivery.', array(), $options),
    'options_callback' => 'commerce_delivery_get_status',
    'default' => ''
  );
  $variables['commerce_delivery_active_status'] = array(
    '#type' => 'options',
    '#title' => t('Active deliveries statuses', array(), $options),
    '#description' => t('Select in which statuses items can be assigned to a delivery.', array(), $options),
    'options_callback' => 'commerce_delivery_get_status',
    'default' => '',
  );
  $variables['commerce_delivery_help_text'] = array(
    'type' => 'string',
    'title' => t('Delivery creation help text', array(), $options),
    'description' => t('Supply an optional help message to be displayed above the delivery form.', array(), $options),
    'default' => '',
  );
}

/**
 * Settings form
 *
 * @param $form
 * @param $form_state
 *
 * @return array
 */
function commerce_delivery_settings_form($form, &$form_state) {
  /*$form['commerce_delivery_status_options'] = array(
    '#type' => 'textarea',
    '#title' => t('Delivery status options'),
    '#description' => t('Supply status options. Format is "id|label". Take note that lower id get priority when assigning items to random deliveries.'),
    '#default_value' => variable_get('commerce_delivery_status_options', "0|new\n1|pending\n2|delivered\n3|on hold\n4|cancelled"),
  );
  $form['commerce_delivery_default_status'] = array(
    '#type' => 'select',
    '#title' => t('Delivery default status'),
    '#description' => t('Select the default status assigned to a new delivery.'),
    '#options' => commerce_delivery_get_status(),
    '#default_value' => variable_get('commerce_delivery_default_status', ''),
  );
  $form['commerce_delivery_active_status'] = array(
    '#type' => 'select',
    '#title' => t('Active deliveries statuses'),
    '#description' => t('Select in which statuses items can be assigned to a delivery.'),
    '#options' => commerce_delivery_get_status(),
    '#default_value' => variable_get('commerce_delivery_active_status', ''),
    '#multiple' => TRUE,
  );
  $form['commerce_delivery_help_text'] = array(
    '#type' => 'textarea',
    '#title' => t('Delivery creation help text'),
    '#description' => t('Supply an optional help message to be displayed above the delivery form.'),
    '#default_value' => variable_get('commerce_delivery_help_text', ''),
  );
*/
  $form = drupal_get_form('variable_module_form', 'commerce_delivery', $form, $form_state);
  return system_settings_form($form);
}

/**
 * Implements hook_views_api().
 */
function commerce_delivery_views_api() {
  return array(
    'api' => 3,
    'path' => drupal_get_path('module', 'commerce_delivery') . '/includes',
  );
}

/**
 * Return deliveries by Order ID
 *
 * @param $order_id
 *   The order ID.
 *
 * @param string $limit
 *   'active' for retrieving only deliveries with active status
 *   'all' (default) for everything
 *
 * @return mixed Array of entity stubs as returned by EntityFieldQuery::execute().
 * Array of entity stubs as returned by EntityFieldQuery::execute().
 */
function commerce_delivery_get_deliveries($order_id, $limit = 'all') {
  $query = new EntityFieldQuery;
  $query->entityCondition('entity_type', 'commerce_delivery')
        ->propertyCondition('order_id', $order_id)
        ->propertyOrderBy('status');

  if ($limit == 'active') {
    $query->propertyCondition('status', variable_get_value('commerce_delivery_active_status'));
  }

  return $query->execute();
}

/**
 * Getter callback for Entity API metadata.
 *
 * @param $order
 * @param array $options
 * @param $name
 *
 * @return array
 */
function commerce_order_get_property_delivery($order, array $options, $name) {
  $delivery_stubs = commerce_delivery_get_deliveries($order->order_id);
  if (isset($delivery_stubs['commerce_delivery'])) {
    return array_keys($delivery_stubs['commerce_delivery']);
  }
  return array();
}

/**
 * Callback that returns delivery_ref default values
 *
 * @param $type
 * @param $line_item
 * @param $f
 * @param $i
 * @param $lang
 *
 * @return array
 */
function commerce_delivery_ref_default_value($type, $line_item, $f, $i, $lang) {
  return array(array('value' => 0));
}
